baseURL: https://akc3n.page/
languageCode: en-us
title: akc3n's notes page
theme: WonderMod
copyright: 'akc3n.page [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) 2020-2022 [LICENSE](https://akc3n.page/LICENSE) '
enableRobotsTXT: true
enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: akc3n's notes page
  description: I’m just an ordinary human that loves to learn, solve puzzles, and eat food.
  keywords: [akc3n, notes, note pages, resources, security, privacy, banking apps project, GrapheneOS]
  author: akc3n
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  ShowToc: true
  ShowFullTextinRSS: true

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "Home"
    icon: "/images/avatar.png"

  homeInfoParams:
        Title: akc3n's notes page
        Content: I’m just an ordinary human that loves to learn, solve puzzles, and eat food.

  profileMode:
    enabled: false
    title: "akc3n's notes page" # optional default will be site title
    subtitle: "I’m just an ordinary human that loves to learn, solve puzzles, and eat food."
    imageUrl: "/images/avatar.png" # optional
      # imageTitle: "akc3n" # optional
    buttons:
      - name: Banking apps
        url: https://privsec.dev/banking
      - name: Posts
        url: "/posts"
      - name: Gists
        url: "/gists"
      - name: Links
        url: "/links"

  socialIcons:
    - name: github
      url: "https://github.com/akc3n"
    - name: matrix
      url: "https://matrix.to/#/@akc3n:grapheneos.org"
    - name: twitter
      url: "https://twitter.com/JuriAksenov"
    - name: reddit
      url: "https://reddit.com/u/akc3n"
    - name: flickr
      url: "https://www.flickr.com/people/akc3n/"
    - name: facebook
      url: "https://www.facebook.com/GrapheneOS"
    - name: instagram
      url: "https://www.instagram.com/grapheneos"
    - name: linkedin
      url: "https://www.linkedin.com/company/grapheneos/"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    
  editPost:
    URL: "https://github.com/akc3n/akc3n.page/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

outputs:
  home:
    - HTML
    - JSON # is necessary

markup:
    highlight:
        style: dracula
        noClasses: false
        lineNos: false
        guessSyntax: true

menu:
  main:
    - identifier: About
      name: About
      url: about
      weight: 10
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: Gists
      name: Gists
      url: /gists/
      weight: 30
    - identifier: Links
      name: Resources
      url: links
      weight: 40
    - identifier: Search
      name: Search
      url: /search/
      weight: 50
    - identifier: Banking
      name: Banking apps project
      url: https://privsec.dev/banking
      weight: 60

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: true
    enableDNT: true
    simple: false
  youtube:
    disable: true
    privacyEnhanced: true
