baseURL: https://akc3n.page/
languageCode: en-us
title: akc3n.page
theme: WonderMod
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
enableRobotsTXT: true
enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: akc3n
  description: Just an ordinary human. Love learning, puzzles & food!
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowToc: true
  ShowRssButtonInSectionTermList: false
  ShowFullTextinRSS: true
  ShowCodeCopyButtons: true

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "akc3n.page"

  profileMode:
    enabled: true
    title: "[me@akc3n.page ~]# _" # optional default will be site title
    subtitle: "Just an ordinary human. Love learning, puzzles & food!"
    imageUrl: "/images/avatar.png" # optional
      # imageTitle: "akc3n" # optional
    buttons:
      - name: Archive
        url: "/archives"
      - name: Links
        url: "/links"

  socialIcons:
    - name: github
      url: "https://github.com/akc3n"
    - name: matrix
      url: "https://matrix.to/#/@akc3n:grapheneos.org"
    - name: twitter
      url: "https://twitter.com/JuriAksenov"
    - name: reddit
      url: "https://reddit.com/u/akc3n"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    
  editPost:
    URL: "https://github.com/akc3n/akc3n.page/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

outputs:
  home:
    - HTML
    - JSON # is necessary

markup:
    highlight:
        style: dracula
        noClasses: false
        guessSyntax: true

menu:
  main:
    - identifier: About
      name: About
      url: about
      weight: 10
    - identifier: Archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: Links
      name: Links
      url: links
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 40
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 50

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: true
    enableDNT: true
    simple: false
  youtube:
    disable: true
    privacyEnhanced: true
