baseURL: "https://akc3n.page/"
languageCode: en-us
title: "akc3n's page of notes"
theme: WonderMod
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "akc3n's page of notes"
  description: "Just an ordinary human that loves to learn, solve puzzles, and eat food."
  keywords: [akc3n, Blog, GrapheneOS, Mobile, Android, Security, Privacy, Knowledge, Tips]
  author: akc3n
  defaultTheme: dark
  disableThemeToggle: false

  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  ShowPostNavLinks: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowWordCount: true
  
  disableSpecial1stPost: false
  disableScrollToTop: false

  searchHidden: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "Home"
    icon: "/images/avatar.png"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: akc3n
    subtitle: "Just an ordinary human that loves to learn, solve puzzles, and eat food."
    imageUrl: "/images/avatar.png"
    buttons:
      - name: About
        url: about
      - name: Contact
        url: contact

# HomeInfo Mode
#  homeInfoParams:
#        Title: akc3n's page of notes
#        Content: I’m just an ordinary human that loves to learn, solve puzzles, and eat food.

  socialIcons:
    #- name: rss
    #  url: /index.xml
    - name: github
      url: "https://github.com/akc3n"
    - name: mastodon
      url: "https://grapheneos.social/@akc3n"
    - name: matrix
      url: "https://matrix.to/#/@akc3n:grapheneos.org"
    - name: twitter
      url: "https://twitter.com/GrapheneOS"
    - name: discord
      url: "https://grapheneos.org/discord"
    - name: telegram
      url: "https://t.me/GrapheneOS"
    #- name: reddit
    #  url: "https://reddit.com/u/akc3n"
    #- name: flickr
    #  url: "https://www.flickr.com/people/akc3n/"
    - name: facebook
      url: "https://www.facebook.com/GrapheneOS"
    - name: instagram
      url: "https://www.instagram.com/grapheneos"
    - name: linkedin
      url: "https://www.linkedin.com/company/grapheneos/"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    
  editPost:
    URL: "https://github.com/akc3n/akc3n.page/blob/main/content"
    Text: "Suggest changes" # edit text
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

# Enabling Search
outputs:
  home:
    - HTML
    - JSON # is necessary
    
# Enable Chroma
markup:
    highlight:
        style: dracula
        noClasses: false
        lineNos: false
        guessSyntax: true

menu:
  main:
    - identifier: About
      name: About
      url: about
      weight: 10
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: Gists
      name: Gists
      url: /gists/
      weight: 30
    - identifier: Links
      name: Resources
      url: links
      weight: 40
    - identifier: Blog
      name: Blog
      url: https://privsec.dev/posts/
      weight: 50
    - identifier: Banking
      name: Banking apps project
      url: https://privsec.dev/posts/android/banking-applications-compatibility-with-grapheneos/
      weight: 60

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: true
    enableDNT: true
    simple: false
  youtube:
    disable: true
    privacyEnhanced: true
